name: Clean up

on:
  workflow_run:
    workflows: ["custom_model Process Frontend data on the Backend", "openAIassistant Process Frontend data on the Backend"]
    types:
      - completed

jobs:
  clean_up_response_file:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - name: Wait for 120 seconds (2 mins)
        run: sleep 120

      - name: Get repository files (equivalent to git pull)
        uses: actions/checkout@v2

      - name: Remove file if it exists
        run: 
          if [ -f openAIassistant_response ]; then
            rm openAIassistant_response;
          fi;
          if [ -f custom_model_response ]; then
            rm custom_model_response;
          fi;
        
      - name: Commit and push changes
        run: |
          repoOwner="$(echo '${{ github.repository }}' | cut -d '/' -f 1)";
          repoOwnerEmail="j622amilah@gmail.com";
          repoName="$(echo '${{ github.repository }}' | cut -d '/' -f 2)";
          REPOA_MY_CHATBOT="${{ secrets.REPOA_MY_CHATBOT_TOKEN0 || secrets.REPOA_MY_CHATBOT_TOKEN1 }}";
          
          git config --global user.email ${repoOwnerEmail};
          git config --global user.name ${repoOwner};
          git config --global pull.rebase true;
          git add -A; 
          git diff-index --quiet HEAD || git commit -m "add files" --allow-empty;
          git push https:/${REPOA_MY_CHATBOT}@github.com/${repoOwner}/${repoName}.git
