name: custom_model Process Frontend data on the Backend

on:
  repository_dispatch:
    types: [trigger-event]

jobs:
  call_endpoint_after_trigger:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - name: Get repository files (equivalent to git pull)
        uses: actions/checkout@v2

      - name: Run commands
        run: |
          INPUT_TEXT=$(echo "${{ github.event.client_payload.fromrepob }}");
          model_response="custom_model in progress";
          echo "$model_response" >> custom_model_response;

      - name: Commit and push changes
        run: |
          repoOwner="$(echo "${{ github.repository }}" | cut -d '/' -f 1)";
          repoOwnerEmail="j622amilah@gmail.com";
          repoName="$(echo "${{ github.repository }}" | cut -d '/' -f 2)";
          REPOA_MY_CHATBOT="${{ secrets.REPOA_MY_CHATBOT_TOKEN0 || secrets.REPOA_MY_CHATBOT_TOKEN1 }}";
          
          git config --global user.email ${repoOwnerEmail};
          git config --global user.name ${repoOwner};
          git config --global pull.rebase true; 
          git add -A;
          git diff-index --quiet HEAD || git commit -m "add files";
          git push https:/${REPOA_MY_CHATBOT}@github.com/${repoOwner}/${repoName}.git
