name: Process Frontend data on the Backend

on:
  push:
    branches:
      - main
    paths:
      - '**'

jobs:
  job_name:
    name: obtain input_text from frontend and process it on backend
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: echo "Workflow triggered by adding a file to the main branch"
