name: Process Frontend data on the Backend

on:
  push:
    branches:
      - main
    paths:
      - '**'

jobs:
  job_name:
    name: obtain input_text from frontend and process it on backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Test 0 Create file
        run: echo "input_text received- "+$(cat cb.txt) > response

      - name: Upload file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: name of file to send to repository
          path: response
