name: Updating a GitHub key - REPOA_MY_CHATBOT_TOKEN0

on:
  schedule:
    - cron: '0 0,12 * * *'
      
jobs:
  update_token:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Assign a new value to the secret
        env:
          GH_TOKEN: ${{ secrets.REPOA_MY_CHATBOT_TOKEN0 || github.token }}
        run: |
          repoOwner=$(echo "${{ github.repository }}" | cut -d '/' -f 1);
          repoOwnerEmail="j622amilah@gmail.com";
          repoName=$(echo "${{ github.repository }}" | cut -d '/' -f 2);
          main_directory=$(echo "/home/runner/work");
          cd $main_directory;
          URL=$(echo "https://${{ env.GH_TOKEN }}@github.com/$repoOwner/$repoName.git");
          
          git config --global user.email ${repoOwnerEmail};
          git config --global user.name ${repoOwner};
          git config --global remote.origin.url $URL;
          git config --global --add safe.directory $main_directory;
          git config --global init.defaultBranch main;
          git init;
          
          git remote add origin https://github.com/$repoOwner/$repoName.git;
          git pull origin main;
          
          git branch -m main;
          git branch --set-upstream-to origin/main;
          git checkout main;
          
          gh secret set REPOA_MY_CHATBOT_TOKEN0 --app actions --body ${{ secrets.REPOA_MY_CHATBOT_TOKEN0 }} --org $repoOwner --repos $repoOwner/$repoName
