name: Updating a GitHub key - REPOA_MY_CHATBOT_TOKEN0


on:
  push:
    branches:
      - main

jobs:
  job0_update_REPOA_MY_CHATBOT_TOKEN0:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Get repository files
        uses: actions/checkout@v2
        
      - name: Assign a new value to the secret
        uses: actions/github-script@v6
        env:
          REPOA_MY_CHATBOT_TOKEN0: '${{ secrets.REPOA_MY_CHATBOT_TOKEN0 }}'
        with:
          result-encoding: string
          github-token: ${{ secrets.REPOA_MY_CHATBOT_TOKEN0 || secrets.REPOA_MY_CHATBOT_TOKEN1 }}
          script: |

            // --------------------------------
            
            // Get id information about Github Actions Secret
            const publicKey_str = await github.rest.actions.getRepoPublicKey({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            // --------------------------------
            
            // Re-assign the new_secret_value to Github Actions Secret
            await github.rest.actions.createOrUpdateRepoSecret({
                owner: context.repo.owner,
                repo: context.repo.repo,
                secret_name: 'REPOA_MY_CHATBOT_TOKEN0',
                encrypted_value: btoa(publicKey_str),
                key_id: publicKey_str.data.key_id,
              });
